#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

. /lib/functions.sh

log_msg() {
    local msg="$1"
    logger -t advanced_setup "$msg"
    if [ -t 1 ]; then
        echo "$msg"
    fi
}

extra_command "reprobe_mt7915e" "Reprobe mt7915e to apply updated WED/ATF module options"


smp_mt76() {
OPTIMIZED_FOR="$1"
CPU_LIST=`cat /proc/interrupts | sed -n '1p'`
NUM_OF_CPU=0; for i in $CPU_LIST; do NUM_OF_CPU=`expr $NUM_OF_CPU + 1`; done;
DEFAULT_RPS=0

RPS_IF_LIST=""
NUM_WIFI_CARD=0
WIFI_RADIO1=0
WIFI_RADIO2=0
WIFI_RADIO3=0
WED_ENABLE=0

WIFI_MODULE_LIST='mt7915e mt7996e'

get_if_info()
{
	# try to get all wifi and eth net interface.
	log_msg "[smp_affinity] Fetching all Wi-Fi and ethernet interfaces"
	NET_IF_LIST=`ls /sys/class/net`
	for vif in $NET_IF_LIST;
	do
		if [[ "$vif" == "eth"* ]] ||  \
		[[ "$vif" == "lan"* ]] || [[ "$vif" == "wan"* ]] || \
		[[ "$vif" == "wlan"* ]] || [[ "$vif" == "phy"* ]]; then
			RPS_IF_LIST="$RPS_IF_LIST $vif"
		fi
	done;
	log_msg "[smp_affinity] RPS_IF_LIST = $RPS_IF_LIST"

	# try to get wifi physical card num.
	log_msg "[smp_affinity] Fetching Wi-Fi physical card number"
	VIRTUAL_RADIO_LIST=`ls -l /sys/class/ieee80211/ | awk -F 'devices' '{print $2}' | awk -F 'phy' '{print $1}' | uniq`
	for v in $VIRTUAL_RADIO_LIST;
	do
		NUM_WIFI_CARD=`expr $NUM_WIFI_CARD + 1`
		log_msg "[smp_affinity] Physical radio $v"
		if [[ $v == *"wmac"* ]]; then
			WIFI_RADIO1=1
		fi

		if [[ $v == *"wbsys"* ]]; then
			WIFI_RADIO1=1
		fi

		if [[ $v == *"pci0000"* ]]; then
			WIFI_RADIO2=1
		fi

		if [[ $v == *"pci0001"* ]]; then
			WIFI_RADIO3=1
		fi
	done;


	for v in $WIFI_MODULE_LIST;
	do
		if [[ -f "/sys/module/$v/parameters/wed_enable" ]]; then
			WED_ENABLE_LIST=`cat /sys/module/$v/parameters/wed_enable`
			log_msg "[smp_affinity] WED enabled in module $v = $WED_ENABLE_LIST"
			if [[ $WED_ENABLE_LIST == "Y" ]]; then
				WED_ENABLE=1
			fi
		fi
	done;
	log_msg "[smp_affinity] NUM_WIFI_CARD = $NUM_WIFI_CARD"
	log_msg "[smp_affinity] Platform Wi-Fi enabled = $WIFI_RADIO1"
	log_msg "[smp_affinity] PCIe1 Wi-Fi enabled = $WIFI_RADIO2"
	log_msg "[smp_affinity] PCIe2 Wi-Fi enabled = $WIFI_RADIO3"
	log_msg "[smp_affinity] WED enabled = $WED_ENABLE"
}

# $1: CPU#
# $2: irq list for added.
CPU_AFFINITY_ADD()
{
	eval oval=\$CPU${1}_AFFINITY
	eval CPU${1}_AFFINITY=\"\$CPU${1}_AFFINITY $2\"
}

# $1: CPU#
# $2: Interface name for added.
CPU_RPS_ADD()
{
	eval oval=\$CPU${1}_RPS
	eval CPU${1}_RPS=\"\$CPU${1}_RPS $2\"
	log_msg "[smp_affinity] CPU${1}_RPS=\"\$CPU${1}_RPS $2\""
}

MT7988()
{
	num_of_wifi=$1
	DEFAULT_RPS=0

	#Physical IRQ# setting
	#Ethernet RSS feature enables 4 Rx rings
	eth_irq_rx0=221
	eth_irq_rx1=222
	eth_irq_rx2=223
	eth_irq_rx3=224
	eth_irq_tx=229
	wifi1_irq_pcie0=524288
	wifi1_irq_pcie1=134742016
	wifi2_irq_pcie0=
	wifi2_irq_pcie1=

	if [[ "$WED_ENABLE" -eq "1" ]]; then
		log_msg "[smp_affinity] Settig up WED iptables rules"
		#TCP Binding
		iptables -D FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		iptables -I FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		ip6tables -D FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		ip6tables -I FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		#UDP Binding
		iptables -D FORWARD -p udp -j FLOWOFFLOAD --hw
		iptables -I FORWARD -p udp -j FLOWOFFLOAD --hw
		ip6tables -D FORWARD -p udp -j FLOWOFFLOAD --hw
		ip6tables -I FORWARD -p udp -j FLOWOFFLOAD --hw
		#Multicast skip Binding
		iptables -D FORWARD -m pkttype --pkt-type multicast -j ACCEPT
		iptables -I FORWARD -m pkttype --pkt-type multicast -j ACCEPT
		ip6tables -D FORWARD -m pkttype --pkt-type multicast -j ACCEPT
		ip6tables -I FORWARD -m pkttype --pkt-type multicast -j ACCEPT
	fi

	for vif in $NET_IF_LIST;
	do
		if [[ "$vif" == "wlan"* ]] || [[ "$vif" == "phy"* ]]; then
			WIFI_IF_LIST="$WIFI_IF_LIST $vif"
		fi
	done;
	log_msg "[smp_affinity] $WIFI_IF_LIST = $WIFI_IF_LIST"
	# Please update the CPU binding in each cases.
	# CPU#_AFFINITY="add binding irq number here"
	# CPU#_RPS="add binding interface name here"
	if [ "$num_of_wifi" = "0" ]; then
		CPU0_AFFINITY="$eth_irq_rx0 $eth_irq_tx"
		CPU1_AFFINITY="$eth_irq_rx1"
		CPU2_AFFINITY="$eth_irq_rx2"
		CPU3_AFFINITY="$eth_irq_rx3"

		CPU0_RPS="$RPS_IF_LIST"
		CPU1_RPS="$RPS_IF_LIST"
		CPU2_RPS="$RPS_IF_LIST"
		CPU3_RPS="$RPS_IF_LIST"
	else
		#we bound all wifi card to cpu0 and bound eth to cpu
		CPU0_AFFINITY=""
		CPU1_AFFINITY=""
		CPU2_AFFINITY="$eth_irq_rx0 $eth_irq_rx1 $eth_irq_tx"
		CPU3_AFFINITY="$eth_irq_rx2 $eth_irq_rx3"

		CPU0_RPS="$WIFI_IF_LIST"
		CPU1_RPS="$WIFI_IF_LIST"
		CPU2_RPS=""
		CPU3_RPS=""
	fi
	log_msg "[smp_affinity] CPU0_AFFINITY = $CPU0_AFFINITY"
	log_msg "[smp_affinity] CPU1_AFFINITY = $CPU1_AFFINITY"
	log_msg "[smp_affinity] CPU2_AFFINITY = $CPU2_AFFINITY"
	log_msg "[smp_affinity] CPU3_AFFINITY = $CPU3_AFFINITY"
}

MT7986()
{
	num_of_wifi=$1
	DEFAULT_RPS=0

	#Physical IRQ# setting
	#Ethernet RSS feature enables 4 Rx rings
	eth_irq_rx0=221
	eth_irq_rx1=222
	eth_irq_rx2=223
	eth_irq_rx3=224
	eth_irq_tx=229
	wifi1_irq=
	wifi2_irq=
	wifi3_irq=

	if [[ "$WED_ENABLE" -eq "1" ]]; then
		log_msg "[smp_affinity] Settig up WED iptables rules"
		#TCP Binding
		iptables -D FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		iptables -I FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		ip6tables -D FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		ip6tables -I FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		#UDP Binding
		iptables -D FORWARD -p udp -j FLOWOFFLOAD --hw
		iptables -I FORWARD -p udp -j FLOWOFFLOAD --hw
		ip6tables -D FORWARD -p udp -j FLOWOFFLOAD --hw
		ip6tables -I FORWARD -p udp -j FLOWOFFLOAD --hw
		#Multicast skip Binding
		iptables -D FORWARD -m pkttype --pkt-type multicast -j ACCEPT
		iptables -I FORWARD -m pkttype --pkt-type multicast -j ACCEPT
		ip6tables -D FORWARD -m pkttype --pkt-type multicast -j ACCEPT
		ip6tables -I FORWARD -m pkttype --pkt-type multicast -j ACCEPT

		#AX6000 AX7800 - SOC
		if [[ "$WIFI_RADIO1" -eq "1" ]]; then
			wifi1_irq=238
		fi
		#AX7800 - PCIE0
		if [[ "$WIFI_RADIO2" -eq "1" ]]; then
			wifi2_irq=237
		fi
		#AX7800 - PCIE1
		#if [[ "$WIFI_RADIO3" -eq "1" ]]; then
		#	wifi3_irq=239
		#fi
	else
		#AX6000 AX7800 - SOC
		if [[ "$WIFI_RADIO1" -eq "1" ]]; then
			wifi1_irq=245
		fi
		#AX7800 - PCIE0
		if [[ "$WIFI_RADIO2" -eq "1" ]]; then
			wifi2_irq=246
		fi
		#AX7800 - PCIE1
		#if [[ "$WIFI_RADIO3" -eq "1" ]]; then
		#	wifi3_irq=247
		#fi
	fi

	for vif in $NET_IF_LIST;
	do
		if [[ "$vif" == "wlan"* ]] || [[ "$vif" == "phy"* ]]; then
			WIFI_IF_LIST="$WIFI_IF_LIST $vif"
		fi
	done;
	log_msg "[smp_affinity] $WIFI_IF_LIST = $WIFI_IF_LIST"
	# Please update the CPU binding in each cases.
	# CPU#_AFFINITY="add binding irq number here"
	# CPU#_RPS="add binding interface name here"
	if [ "$num_of_wifi" = "0" ]; then
		CPU0_AFFINITY="$eth_irq_rx0"
		CPU1_AFFINITY="$eth_irq_rx1 $eth_irq_tx"
		CPU2_AFFINITY="$eth_irq_rx2"
		CPU3_AFFINITY="$eth_irq_rx3"

		CPU0_RPS=""
		CPU1_RPS=""
		CPU2_RPS=""
		CPU3_RPS=""
	else
		#we bound all wifi card to cpu1 and bound eth to cpu0
		CPU0_AFFINITY="$eth_irq_rx0"
		CPU1_AFFINITY="$eth_irq_rx1 $eth_irq_tx"
		CPU2_AFFINITY="$eth_irq_rx2 $wifi2_irq $wifi3_irq"
		CPU3_AFFINITY="$eth_irq_rx3 $wifi1_irq"

		CPU0_RPS="$WIFI_IF_LIST"
		CPU1_RPS="$WIFI_IF_LIST"
		CPU2_RPS="$WIFI_IF_LIST"
		CPU3_RPS="$WIFI_IF_LIST"
	fi
	log_msg "[smp_affinity] CPU0_AFFINITY = $CPU0_AFFINITY"
	log_msg "[smp_affinity] CPU1_AFFINITY = $CPU1_AFFINITY"
	log_msg "[smp_affinity] CPU2_AFFINITY = $CPU2_AFFINITY"
	log_msg "[smp_affinity] CPU3_AFFINITY = $CPU3_AFFINITY"
}

gl_mt6000()
{
	num_of_wifi=$1
	DEFAULT_RPS=0

	#Physical IRQ# setting
	#Ethernet RSS feature enables 4 Rx rings
	eth_irq_rx0=221
	eth_irq_rx1=222
	eth_irq_rx2=223
	eth_irq_rx3=224
	eth_irq_tx=229
	
	
	if [[ "$WED_ENABLE" -eq "1" ]]; then
		wifi1_irq=237
	else
		wifi1_irq=245
	fi

	for vif in $NET_IF_LIST;
	do
		if [[ "$vif" == "wlan"* ]] || [[ "$vif" == "phy"* ]]; then
			WIFI_IF_LIST="$WIFI_IF_LIST $vif"
		fi
	done;
	
	WAN_IF_LIST=""

	for iface in $(uci show network | grep "=interface" | cut -d '.' -f 2 | cut -d '=' -f1 | sort -u); do
		proto=$(uci get network.$iface.proto 2>/dev/null)
		role=$(uci get network.$iface.role 2>/dev/null)

		if [ "$proto" = "dhcp" ] || [ "$proto" = "pppoe" ] || [ "$role" = "wan" ]; then
			device=$(uci get network.$iface.device 2>/dev/null)

			for dev in $device; do
				if echo "$dev" | grep -q '\.'; then
					base_if=$(uci show network | grep "device..*name='$dev'" | cut -d. -f2 | while read devsec; do
						uci get network.$devsec.ifname 2>/dev/null
					done)

					if [ -n "$base_if" ]; then
						WAN_IF_LIST="$WAN_IF_LIST $base_if"
					fi

				elif [ -d "/sys/class/net/$dev" ]; then
					WAN_IF_LIST="$WAN_IF_LIST $dev"

				else
					alias_if=$(uci get network.$dev.ifname 2>/dev/null)
					if [ -n "$alias_if" ]; then
						WAN_IF_LIST="$WAN_IF_LIST $alias_if"
					fi
				fi
			done
		fi
	done

	WAN_IF_LIST=$(echo "$WAN_IF_LIST" | tr ' ' '\n' | sort -u | tr '\n' ' ')
	
	BRIDGE_MEMBERS=""

	if [ -d /sys/class/net/br-lan/brif ]; then
		for member in $(ls /sys/class/net/br-lan/brif); do
			case "$member" in
				wlan*|phy*)
					continue
					;;
			esac

			if echo "$member" | grep -q '\.'; then
				parent="${member%%.*}"
				BRIDGE_MEMBERS="$BRIDGE_MEMBERS $parent"
			else
				BRIDGE_MEMBERS="$BRIDGE_MEMBERS $member"
			fi
		done
	fi

	BRIDGE_MEMBERS=$(echo $BRIDGE_MEMBERS | tr ' ' '\n' | sort -u | tr '\n' ' ')
	
	log_msg "[smp_affinity] WAN_IF_LIST = $WAN_IF_LIST"
	log_msg "[smp_affinity] BRIDGE_LIST = $BRIDGE_MEMBERS"
	log_msg "[smp_affinity] WIFI_IF_LIST = $WIFI_IF_LIST"
	
	# Please update the CPU binding in each cases.
	# CPU#_AFFINITY="add binding irq number here"
	# CPU#_RPS="add binding interface name here"
	
	#we bound all wifi card to cpu1 and bound eth to cpu0
	CPU0_AFFINITY="$eth_irq_rx0"
	CPU1_AFFINITY="$eth_irq_rx1 $eth_irq_tx"
	CPU2_AFFINITY="$eth_irq_rx2 $wifi2_irq $wifi3_irq"
	CPU3_AFFINITY="$eth_irq_rx3 $wifi1_irq"
	
	rps_type=$(uci get advanced.@advanced_packet_steering[0].advanced_packet_steering_enable 2>/dev/null)

	if [ -z "$rps_type" ] || [ "$rps_type" = "1" ]; then
		CPU0_RPS="$WIFI_IF_LIST"
		CPU1_RPS="$WIFI_IF_LIST"
		CPU2_RPS="$WIFI_IF_LIST"
		CPU3_RPS="$WIFI_IF_LIST"
	elif  [ "$rps_type" = "2" ]; then
		CPU0_RPS="$BRIDGE_MEMBERS $WIFI_IF_LIST"
		CPU1_RPS="$WAN_IF_LIST $WIFI_IF_LIST"
		CPU2_RPS="$WAN_IF_LIST $WIFI_IF_LIST"
		CPU3_RPS="$WAN_IF_LIST $WIFI_IF_LIST"
	fi

}

MT7981()
{
	num_of_wifi=$1
	DEFAULT_RPS=0

	#Physical IRQ# setting
	eth_irq_rx=221
	eth_irq_tx=229
	wifi1_irq=
	wifi2_irq=
	wifi3_irq=

	#AX3000
	if [[ "$WED_ENABLE" -eq "1" ]]; then
		log_msg "[smp_affinity] Settig up WED iptables rules"
		#TCP Binding
		iptables -D FORWARD -p tcp -m conntrack --ctstate	\
				RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		iptables -I FORWARD -p tcp -m conntrack --ctstate	\
				RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		ip6tables -D FORWARD -p tcp -m conntrack --ctstate	\
				RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		ip6tables -I FORWARD -p tcp -m conntrack --ctstate	\
				RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
		#UDP Binding
		iptables -D FORWARD -p udp -j FLOWOFFLOAD --hw
		iptables -I FORWARD -p udp -j FLOWOFFLOAD --hw
		ip6tables -D FORWARD -p udp -j FLOWOFFLOAD --hw
		ip6tables -I FORWARD -p udp -j FLOWOFFLOAD --hw
		#Multicast skip Binding
		iptables -D FORWARD -m pkttype --pkt-type multicast -j ACCEPT
		iptables -I FORWARD -m pkttype --pkt-type multicast -j ACCEPT
		ip6tables -D FORWARD -m pkttype --pkt-type multicast -j ACCEPT
		ip6tables -I FORWARD -m pkttype --pkt-type multicast -j ACCEPT

		if [[ "$WIFI_RADIO1" -eq "1" ]]; then
			wifi1_irq=237
		fi
	else
		if [[ "$WIFI_RADIO1" -eq "1" ]]; then
			wifi1_irq=245
		fi
	fi

	# Please update the CPU binding in each cases.
	# CPU#_AFFINITY="add binding irq number here"
	# CPU#_RPS="add binding interface name here"
	if [ "$num_of_wifi" = "0" ]; then
		CPU0_AFFINITY="$eth_irq_rx"
		CPU1_AFFINITY="$eth_irq_tx"

		CPU0_RPS="$RPS_IF_LIST"
		CPU1_RPS="$RPS_IF_LIST"
	else
		#we bound all wifi card to cpu0 and bound eth to cpu1
		CPU0_AFFINITY="$wifi1_irq $wifi2_irq $wifi3_irq"
		CPU1_AFFINITY="$eth_irq_rx $eth_irq_tx"

		CPU0_RPS="$RPS_IF_LIST"
		CPU1_RPS="$RPS_IF_LIST"
	fi
	log_msg "[smp_affinity] CPU0_AFFINITY = $CPU0_AFFINITY"
	log_msg "[smp_affinity] CPU1_AFFINITY = $CPU1_AFFINITY"
}

gl_mt3000()
{
	num_of_wifi=$1
	DEFAULT_RPS=0

	#Physical IRQ# setting
	eth_irq_rx=229
	eth_irq_tx=230
	wifi1_irq=
	wifi2_irq=
	wifi3_irq=

	#AX3000
	if [[ "$WED_ENABLE" -eq "1" ]]; then
		
		if [[ "$WIFI_RADIO1" -eq "1" ]]; then
			wifi1_irq=237
		fi
	else
		if [[ "$WIFI_RADIO1" -eq "1" ]]; then
			wifi1_irq=245
		fi
	fi

	# Please update the CPU binding in each cases.
	# CPU#_AFFINITY="add binding irq number here"
	# CPU#_RPS="add binding interface name here"
	if [ "$num_of_wifi" = "0" ]; then
		CPU0_AFFINITY="$eth_irq_rx"
		CPU1_AFFINITY="$eth_irq_tx"

		CPU0_RPS="$RPS_IF_LIST"
		CPU1_RPS="$RPS_IF_LIST"
	else
		#we bound all wifi card to cpu0 and bound eth to cpu1
		CPU0_AFFINITY="$wifi1_irq $wifi2_irq $wifi3_irq"
		CPU1_AFFINITY="$eth_irq_rx $eth_irq_tx"

		CPU0_RPS="$RPS_IF_LIST"
		CPU1_RPS="$RPS_IF_LIST"
	fi
	log_msg "[smp_affinity] CPU0_AFFINITY = $CPU0_AFFINITY"
	log_msg "[smp_affinity] CPU1_AFFINITY = $CPU1_AFFINITY"
}

MT7622()
{
	num_of_wifi=$1
	DEFAULT_RPS=0

	#Physical IRQ# setting
	eth0_irq=224
	eth1_irq=225
	wifi1_irq=
	wifi2_irq=
	wifi3_irq=
	#AX1200 AX3200
	if [[ "$WIFI_RADIO1" -eq "1" ]]; then
		wifi1_irq=211
	fi
	#AX1800 AX3200
	if [[ "$WIFI_RADIO2" -eq "1" ]]; then
		wifi2_irq=214
	fi
	#AX3600
	if [[ "$WIFI_RADIO3" -eq "1" ]]; then
		wifi3_irq=215
	fi

	# Please update the CPU binding in each cases.
	# CPU#_AFFINITY="add binding irq number here"
	# CPU#_RPS="add binding interface name here"
	if [ "$num_of_wifi" == "0" ]; then
		CPU0_AFFINITY="$eth0_irq"
		CPU1_AFFINITY="$eth1_irq"

		CPU0_RPS="$RPS_IF_LIST"
		CPU1_RPS="$RPS_IF_LIST"
	else
		#we bound all wifi card to cpu0 and bound eth to cpu1
		CPU0_AFFINITY="$wifi1_irq $wifi2_irq $wifi3_irq"
		CPU1_AFFINITY="$eth0_irq $eth1_irq"

		CPU0_RPS="$RPS_IF_LIST"
		CPU1_RPS="$RPS_IF_LIST"
	fi

	log_msg "[smp_affinity] CPU0_AFFINITY = $CPU0_AFFINITY"
	log_msg "[smp_affinity] CPU1_AFFINITY = $CPU1_AFFINITY"
}

setup_model()
{
	board=$(board_name)
	log_msg "[smp_affinity] Board name: $board"
	num_of_wifi=$NUM_WIFI_CARD

	if [[ $board == *"7988"* ]]; then
		log_msg "[smp_affinity] setup_model: MT7988 NUM_WIFI_CARD=$num_of_wifi"
		MT7988 $num_of_wifi
	elif [[ $board == *"7986"* ]]; then
		log_msg "[smp_affinity] setup_model: MT7986 NUM_WIFI_CARD=$num_of_wifi"
		MT7986 $num_of_wifi
	elif [[ $board == *"gl-mt6000"* ]]; then
		log_msg "[smp_affinity] setup_model: gl-mt6000 NUM_WIFI_CARD=$num_of_wifi"
		gl_mt6000 $num_of_wifi
	elif [[ $board == *"7981"* ]]; then
		log_msg "[smp_affinity] setup_model: MT7981 NUM_WIFI_CARD=$num_of_wifi"
		MT7981 $num_of_wifi
	elif [[ $board == *"gl-mt3000"* ]]; then
		log_msg "[smp_affinity] setup_model: gl-mt3000 NUM_WIFI_CARD=$num_of_wifi"
		gl_mt3000 $num_of_wifi
	elif [[ $board == *"7622"* ]]; then
		log_msg "[smp_affinity] setup_model: MT7622 NUM_WIFI_CARD=$num_of_wifi"
		MT7622 $num_of_wifi
	elif [[ $board == *"bpi-r4"* ]]; then
		log_msg "[smp_affinity] setup_model: bpi-r4 NUM_WIFI_CARD=$num_of_wifi"
		MT7988 $num_of_wifi
	fi
}

get_virtual_irq()
{
	PHY_POS=`expr $NUM_OF_CPU + 3` #physical irq # position in /proc/interrups may vary with the number of CPU up
	target_phy_irq=$1
	cat /proc/interrupts | sed 's/:/ /g'| awk '$1 ~ /^[0-9]+$/' | while read line
	do
		set -- $line
		phy_irq=$(eval "echo \$$PHY_POS")
		if [ $phy_irq == $target_phy_irq ]; then
			echo $1
			return
		fi
	done
}

set_rps_cpu_bitmap()
{
	log_msg "[smp_affinity] Scanning binding interfaces of each CPU"
	# suppose the value of interface_var is null or hex
	num=0
	while [ "$num" -lt "$NUM_OF_CPU" ];do
		cpu_bit=$((2 ** $num))
		eval rps_list=\$CPU${num}_RPS
		log_msg "[smp_affinity] CPU$num: rps_list=$rps_list"
		for i in $rps_list; do
			var=${VAR_PREFIX}_${i//'-'/_}
			var=${var//'.'/_}
			eval ifval=\$$var
			log_msg "[smp_affinity] [var val before] $var=$ifval"
			if [ -z "$ifval" ]; then
				eval $var=$cpu_bit
			else
				eval $var=`expr $ifval + $cpu_bit`
			fi
			eval ifval=\$$var
			log_msg "[smp_affinity] [rps val after]$i=$ifval"
		done
		num=`expr $num + 1`
	done
}

# $1: The default rps value. If rps of the interface is not setup, set $1 to it
set_rps_cpus()
{
	log_msg "[smp_affinity] Setting up RPS on interfaces: $RPS_IF_LIST"
	for i in $RPS_IF_LIST; do
		var=${VAR_PREFIX}_${i//'-'/_}
		var=${var//'.'/_}
		eval cpu_map=\$$var
		if [ -d /sys/class/net/$i ]; then
			if [ -n "$cpu_map" ]; then
				cpu_map=`printf '%x' $cpu_map`
			elif [ -n "$1" ]; then
				cpu_map="$1"
			fi

			if [ -n "$cpu_map" ]; then
				for rxq in /sys/class/net/$i/queues/rx-*; do
					[ -d "$rxq" ] || continue
					log_msg "[smp_affinity] echo $cpu_map > $rxq/rps_cpus"
					echo $cpu_map > "$rxq/rps_cpus"
				done
			fi
		fi
	done
}

set_smp_affinity()
{
	log_msg "[smp_affinity] Setting up affinity of each physical IRQ"
	num=0
	irqbalance_enabled=$(uci get irqbalance.@irqbalance[0].enabled 2>/dev/null || echo 0)
	if [ "$irqbalance_enabled" == 1 ]; then
		log_msg "[smp_affinity] irqbalance is enabled"
		irqbalance_excluded_irqs=$(uci get irqbalance.@irqbalance[0].banirq 2>/dev/null)
		irqbalance_settings_modified=0
	fi
	while [ "$num" -lt "$NUM_OF_CPU" ];do
		eval smp_list=\$CPU${num}_AFFINITY
		for i in $smp_list; do
			cpu_bit=$((2 ** $num))
			virq=$(get_virtual_irq $i)
			#virq=$i
			log_msg "[smp_affinity] IRQ p2v $i --> $virq"
			if [ ! -z $virq ]; then
				#log_msg "[smp_affinity] echo $cpu_bit > /proc/irq/$virq/smp_affinity"
				echo $cpu_bit > /proc/irq/$virq/smp_affinity
				case "$irqbalance_enabled: $irqbalance_excluded_irqs " in
					1:*" $virq "*) log_msg "[smp_affinity] IRQ $virq already excluded from irqbalance" ;;
					1:*)
						log_msg "[smp_affinity] Adding IRQ $virq to irqbalance exclusions"
						echo $virq >> /tmp/smp_affinity_irqs
						irqbalance_settings_modified=1
						;;
				esac
			fi
		done
		num=`expr $num + 1`
	done
	if [ -f /tmp/smp_affinity_irqs ] && [ "$irqbalance_settings_modified" == 1 ]; then
		log_msg "[smp_affinity] Applying irqbalance changes"
		if /etc/init.d/irqbalance status > /dev/null 2>&1; then
			/etc/init.d/irqbalance restart
		fi
	fi
}


log_msg "[smp_affinity] Setting up RPS and affinity"
log_msg "[smp_affinity] NUM_OF_CPU=$NUM_OF_CPU"
VAR_PREFIX="autogen"
get_if_info
setup_model

rps_setting=$(uci get network.globals.packet_steering 2>/dev/null)
rps_type=$(uci get advanced.@advanced_packet_steering[0].advanced_packet_steering_enable 2>/dev/null)

if [ -z "$rps_setting" ] || [ "$rps_setting" = "0" ]; then
	if [ -z "$rps_type" ] || [ "$rps_type" != "0" ]; then
		set_rps_cpu_bitmap
		set_rps_cpus $DEFAULT_RPS
	else
		log_msg "[smp_affinity] RPS is disabled"
	fi
else
	log_msg "[smp_affinity] RPS is set up by packet steering script"
fi


set_smp_affinity
#end of file
}

mtk_offloading()
{
	mtk_offloading_enable=$(uci get advanced.@defaults[0].mtk_offloading_enable 2>/dev/null || echo "x")
	if [ "$mtk_offloading_enable" == "1" ]; then
			log_msg "[smp_affinity] Enabling mtk offloading"
			#TCP Binding
			iptables -I FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
			ip6tables -I FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
			#UDP Binding
			iptables -I FORWARD -p udp -j FLOWOFFLOAD --hw
			ip6tables -I FORWARD -p udp -j FLOWOFFLOAD --hw
			#Multicast skip Binding
			iptables -I FORWARD -m pkttype --pkt-type multicast -j ACCEPT
			ip6tables -I FORWARD -m pkttype --pkt-type multicast -j ACCEPT
	elif [ "$mtk_offloading_enable" == 0 ]; then
			log_msg "[smp_affinity] Disabling mtk offloading"
			#TCP Binding
			iptables -D FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
			ip6tables -D FORWARD -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw
			#UDP Binding
			iptables -D FORWARD -p udp -j FLOWOFFLOAD --hw
			ip6tables -D FORWARD -p udp -j FLOWOFFLOAD --hw
			#Multicast skip Binding
			iptables -D FORWARD -m pkttype --pkt-type multicast -j ACCEPT
			ip6tables -D FORWARD -m pkttype --pkt-type multicast -j ACCEPT
	fi
}

load_mt7915e_from_modules_file()
{
	local module_file="/etc/modules.d/mt7915e"
	local modline

	[ -e "$module_file" ] || return 1

	modline=$(cat "$module_file" 2>/dev/null)
	[ -n "$modline" ] || modline="mt7915e"

	set -- $modline
	/sbin/modprobe "$@"
}

wait_for_mt7915e_runtime()
{
	local tries=0

	while [ "$tries" -lt 10 ]; do
		[ -e /sys/module/mt7915e/parameters/wed_enable ] && return 0
		sleep 1
		tries=$((tries + 1))
	done

	return 1
}

reprobe_mt7915e()
{
	local reprobe_ok=0

	log_msg "[mt7915e] Reloading module to apply changes"

	/sbin/wifi down >/dev/null 2>&1
	sleep 2

	if grep -q '^mt7915e ' /proc/modules 2>/dev/null; then
		if ! /sbin/modprobe -r mt7915e >/dev/null 2>&1 && \
		   ! /sbin/rmmod mt7915e >/dev/null 2>&1; then
			log_msg "[mt7915e] Failed to unload module. Attempting to re-enable Wi-Fi"
			/sbin/wifi up >/dev/null 2>&1
			return 1
		fi
	fi

	sleep 2

	if ! load_mt7915e_from_modules_file >/dev/null 2>&1; then
		log_msg "[mt7915e] Failed to reload module from /etc/modules.d/mt7915e"
	else
		reprobe_ok=1
	fi

	if [ "$reprobe_ok" -eq 1 ] && ! wait_for_mt7915e_runtime; then
		log_msg "[mt7915e] Module runtime files not ready after reload"
		reprobe_ok=0
	fi

	/sbin/wifi up >/dev/null 2>&1
	sleep 3

	if [ "$reprobe_ok" -ne 1 ]; then
		log_msg "[mt7915e] Module relode incomplete. Attempt to re-enable Wi-Fi was made"
		return 1
	fi

	smp_mt76
	enable_HQoS
	usb_setup
	hw_atf_setup

	log_msg "[mt7915e] Module reload completed"
	return 0
}

sync_mt7915e_airtime_module_options()
{
	MODULE_FILE="/etc/modules.d/mt7915e"
	atf=$(uci get advanced.@defaults[0].atf_enable 2>/dev/null || echo "0")
	hwatf=$(uci get advanced.@defaults[0].hw_atf_enable 2>/dev/null || echo "0")

	if [ "$atf" != "1" ] && [ "$hwatf" = "1" ]; then
		log_msg "[HW-ATF] HW-ATF requires ATF. Disabling HW-ATF"
		uci set advanced.@defaults[0].hw_atf_enable='0'
		uci commit advanced
		hwatf=0
	fi

	if [ -e "$MODULE_FILE" ]; then
		old_content=$(cat "$MODULE_FILE" 2>/dev/null)
		new_line="mt7915e"

		set -- $old_content
		for token in "$@"; do
			case "$token" in
				mt7915e|expose_airtime_fairness=*)
					;;
				*)
					case " $new_line " in
						*" $token "*)
							;;
						*)
							new_line="$new_line $token"
							;;
					esac
					;;
			esac
		done

		if [ "$atf" = "1" ]; then
			new_line="$new_line expose_airtime_fairness=0"
		fi

		if [ "$old_content" != "$new_line" ]; then
			printf '%s\n' "$new_line" > "$MODULE_FILE"
			log_msg "[HW-ATF] $MODULE_FILE updated with '$new_line'. Reboot is required to change Airtime Fairness mode"
			echo "1"
			return 0
		fi
	fi

	echo "0"
}

hw_atf_setup()
{
	FILE="/sys/kernel/debug/ieee80211/phy0/mt76/vow"
	sync_mt7915e_airtime_module_options >/dev/null

	if [ -e "$FILE" ]; then
		log_msg "[HW-ATF] HW-ATF is available"
		if [ "$atf" = "1" ]; then
			echo 'vow_atf_en=1' > /sys/kernel/debug/ieee80211/phy0/mt76/vow
		else
			echo 'vow_atf_en=0' > /sys/kernel/debug/ieee80211/phy0/mt76/vow
		fi
		
		if [ "$atf" = "1" ] && [ "$hwatf" = "1" ]; then
			echo 'vow_watf_en=1' > /sys/kernel/debug/ieee80211/phy0/mt76/vow
		else
			echo 'vow_watf_en=0' > /sys/kernel/debug/ieee80211/phy0/mt76/vow
		fi
		echo 'show_vow_info' > /sys/kernel/debug/ieee80211/phy0/mt76/vow
	fi
}

enable_HQoS()
{
	FILE="/sbin/mtkhnat"
	if [ -e "$FILE" ]; then
		mtkutil_enable=$(uci get mtkhnat.global.enable 2>/dev/null  || echo "x")
		hqos_enable=$(uci get mtkhnat.global.hqos 2>/dev/null  || echo "x")
		if [ $mtkutil_enable == 1 ]; then
			if [ $hqos_enable == 1 ]; then
				/sbin/mtkhnat
				log_msg "[HQoS] mtkhnat_util is enabled and active"
			fi
		fi
	fi
	
}

usb_setup()
{
	usb2=$(uci get advanced.@defaults[0].usb_2 2>/dev/null || echo "x")
	if [ $usb2 == 1 ]; then
		log_msg "[USB] USB port speed is set to 2.0"
		echo 1 > /sys/bus/usb/devices/usb2/2-0:1.0/usb2-port1/disable
	elif [ $usb2 == 0 ]; then
		log_msg "[USB] USB port speed is set to 3.0"
		echo 0 > /sys/bus/usb/devices/usb2/2-0:1.0/usb2-port1/disable
	fi
	
	usbpower=$(uci get advanced.@defaults[0].usb_power 2>/dev/null || echo "x")
	if [ $usbpower == 1 ]; then
		log_msg "[USB] Turning on USB port power"
		echo 1 > /sys/devices/platform/regulator-usb-vbus/usb_vbus_enable
	elif [ $usbpower == 0 ]; then
		log_msg "[USB] Turning off USB port power"
		echo 0 > /sys/devices/platform/regulator-usb-vbus/usb_vbus_enable
	fi
	
	USB2_PATH="/sys/bus/usb/devices/usb2/2-0:1.0/usb2-port1/disable"
	USBPOWER_PATH="/sys/devices/platform/regulator-usb-vbus/usb_vbus_enable"
	status2=$(cat "$USB2_PATH")
	statuspower=$(cat "$USBPOWER_PATH")
	if [ "$status2" -eq 1 ]; then
		log_msg "[USB] USB speed is set to 2.0"
	fi
	if [ "$statuspower" -eq 1 ]; then
		log_msg "[USB] USB port power is enabled"
	else
		log_msg "[USB] USB port power is disabled"
	fi
	
}

clean_irqbalance_config()
{
	if [ -f /tmp/smp_affinity_irqs ]; then
		log_msg "[smp_affinity] Removing irqbalance exceptions"
		rm /tmp/smp_affinity_irqs
		if [ ! -e /tmp/run/procd.shutdown ] && /etc/init.d/irqbalance status >/dev/null 2>&1; then
			/etc/init.d/irqbalance restart
		fi
	fi
}

service_triggers() {
    procd_add_reload_trigger advanced network
}

start_service() {
	log_msg "Starting"
    if [ ! -f /tmp/smp_affinity_started ]; then
		delay=$(uci get advanced.@advanced_packet_steering[0].advanced_packet_steering_delay 2>/dev/null || echo "30")
		log_msg "[smp_affinity] Starting with delay of $delay sec."
		sleep $delay
		echo 1 > /tmp/smp_affinity_started
	fi
	smp_mt76
	enable_HQoS
	usb_setup
	hw_atf_setup
    log_msg "Finished"
}

reload_service() {
    trigger="$1"
    case "$trigger" in
        atf)
			log_msg "Reloading ATF settings"
			if [ "$(sync_mt7915e_airtime_module_options)" = "1" ]; then
				reprobe_mt7915e
			else
				hw_atf_setup
			fi
            ;;
        usb)
			log_msg "Reloading USB settings"
            usb_setup
            ;;
        wed)
			log_msg "Reloading WED"
			reprobe_mt7915e
			;;
        *)
			log_msg "Reloading all settings"
			if [ ! -f /tmp/smp_affinity_started ]; then
				delay=$(uci get advanced.@advanced_packet_steering[0].advanced_packet_steering_delay 2>/dev/null || echo "30")
				log_msg "[smp_affinity] Starting with delay of $delay sec."
				sleep $delay
				echo 1 > /tmp/smp_affinity_started
			fi
			clean_irqbalance_config
			smp_mt76
			enable_HQoS
			usb_setup
			hw_atf_setup
            ;;
    esac
	log_msg "Finished"
}

stop_service() {
    #log_msg "No stop actions defined"
	clean_irqbalance_config
}
