#!/bin/sh

[ "$ACTION" = "ifdown" ] || exit 0

WG_IF=$(ubus call network.interface dump | jsonfilter -e '@.interface[@.proto="wireguard"].interface')
if [ "$INTERFACE" = "$WG_IF" ]; then
    /etc/init.d/firewall reload
fi
