name: Build testing (GitHub-hosted)

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OpenWrt testing for GL-MT6000
    uses: ./.github/workflows/_build_openwrt.yaml
    with:
      config_file: mt6000_testing.config
      check_runner: ubuntu-slim
      build_runner: ubuntu-latest
    permissions:
      contents: write
      actions: write
