name: Build (self-hosted)

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OpenWrt for GL-MT6000
    uses: ./.github/workflows/_build_openwrt.yaml
    with:
      config_file: mt6000_testing.config
      check_runner: self-hosted
      build_runner: self-hosted
      use_ccache: true
    permissions:
      contents: write
      actions: write
