name: Build OpenWrt testing for GL-MT6000

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build_openwrt.yaml
    with:
      config_file: mt6000.config
      check_runner: ubuntu-slim
      build_runner: ubuntu-latest
      install_deps: true
    permissions:
      contents: write
      actions: write
