name: Build (GitHub-hosted)

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      remote_branch:
        description: "Remote branch to build (leave empty for the latest next-* branch)"
        required: false
        default: ""
        type: string
      testing_kernel:
        description: "Build with testing kernel"
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: Build OpenWrt for GL-MT6000
    uses: ./.github/workflows/_build_openwrt.yaml
    with:
      check_runner: ubuntu-slim
      remote_branch: ${{ inputs.remote_branch }}
      build_runner: ubuntu-latest
      use_ccache: true
      config_file: mt6000.config
      testing_kernel: ${{ inputs.testing_kernel }}
    permissions:
      contents: write
      actions: write
